### PR TITLE
Countdown fixes

### LINKED ISSUE #60: Add hours to countdown and make the countdown display 0 after the day

### PR DESCRIPTION
**Pull request by lucaspauker**
close #60

### CODE REVIEW

**Comment by lucaspauker** [comment]
Looks like branch didn't get auto-deployed :(
`Continuous integration has not been set up`

**Comment by theopolisme** [comment]
> Looks like branch didn't get auto-deployed :(
> `Continuous integration has not been set up`

Do you have a Heroku account already / if not plz set one up and let me know the email on the account. I'll then send you an invite to the Heroku org

**Comment by lucaspauker** [comment]
@theopolisme lucas.pauker@gmail.com

**Comment by theopolisme** [comment]
Awesome!! 🎉

**Pull request merged**
