### PR TITLE
Add Linkedin pixel tracking

### PR DESCRIPTION
**Pull request by lucaspauker**
I hope this works to spec for adding linkedin tracking.

The idea is to display the pixel upon clicking the "apply" button.

### CODE REVIEW

**Comment by theopolisme** [comment]
Does this...work? Or does the fact that the user is navigating away break things?

**Comment by theopolisme** [comment]
Question, is there a reason to not just add the `` tag to the root.treehacks site since whenever anybody goes there, it means they're "converted"?

**Comment by lucaspauker** [comment]
@theopolisme Let's talk about this tomorrow--I thought the idea was that we want to see who applies after navigating to the page from linkedin ad.

**Comment by lucaspauker** [comment]
@theopolisme Ok...I think your solution makes a lot more sense. closing this for now....

**Pull request closed without merging**
